baseurl = "https://ihacktoprotect.com/" # Controls base URL
languageCode = "en-US" # Controls site language
title = "I hack to protect" # Homepage title and page title suffix
paginate = 11 # Number of posts to show before paginating
theme = "hyde" # Set default theme
enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
disqusShortname = "" # Optional, add Disqus shortname for comments

[params]
  description = "Adventures in AppSec" 

[menu]

[[menu.main]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/page/about"
[[menu.main]]
  name = "Presentations"
  weight = 2
  identifier = "presentations"
  url = "/page/presentations"
[[menu.main]]
  name = "Categories"
  weight = 3
  identifier = "categories"
  url = "/categories"
[[menu.main]]
  name = "Tags"
  weight = 4
  identifier = "tags"
  url = "/tags"

